[package]
name = "aes_extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10.0"
serde_json = "1.0.139"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.32", features = ["derive"] }
colour = "2.1.0"
